name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ubuntu:
    name: Build - Ubuntu
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Prerequisites
        run: sudo apt-get install -y libcgal-dev ninja-build zsh

      - name: Configure
        run: ./run cmake

      - name: Build
        run: ./run build
